import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import { Popover, Widget } from "@typeform/embed-react";
import { useWindowSize } from "../hooks/useWindowSize";

const formId = "crNvgGG2";

const getCookie = (name) => {
  const match = document.cookie.match(new RegExp(`${name}="([^"]+)"`));
  return (match && match[1]) || null;
};

const clearCookies = () => {
  document.cookie = 'typeform_name="";';
  document.cookie = 'typeform_rating="";';
  window.location.reload();
};

export default function Home() {
  const [typeformName, setTypeformName] = useState(null);
  const [typeformRating, setTypeformRating] = useState(null);
  const isTypeformRatingGood = typeformRating > 5;
  const windowSize = useWindowSize();
  const isMobile = windowSize.width <= 425;
  const widgetWidth = isMobile ? windowSize.width : 720;
  const widgetHeight = isMobile ? windowSize.height : 600;

  // const initializeFromCookies = () => {
  //   setTypeformName(getCookie("typeform_name"));
  //   setTypeformRating(getCookie("typeform_rating"));
  // };

  // useEffect(initializeFromCookies, []);

  const handleTypeformSubmit = async ({ responseId }) => {
    console.log("form submitted, response has id", responseId);
    const response = await fetch(
      `/api/response?id=${formId}&response_id=${responseId}`
    );

    if (response.ok) {
      const { name, rating } = await response.json();
      console.log("Form responses", { name, rating });

      if (name) {
        document.cookie = `typeform_name="${name}";`;
        setTypeformName(name);
      }

      if (rating) {
        document.cookie = `typeform_rating="${rating}";`;
        setTypeformRating(rating);
      }
    }
  };

  const getTooltip = () => {
    if (typeformName) {
      if (typeformRating) {
        const ratingMessage = isTypeformRatingGood
          ? "We are happy you like our website!"
          : "We will try to improve our website!";
        return `Hello, ${typeformName}! ${ratingMessage}`;
      } else {
        return `Hello, ${typeformName} please rate our website.`;
      }
    } else {
      return "Hello, please give us your feedback.";
    }
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <Widget
          key={`${typeformName}-${typeformRating}`}
          id={"tKB4AGVM"}
          tooltip={getTooltip()}
          onSubmit={handleTypeformSubmit}
          width={widgetWidth}
          height={widgetHeight}
        />
      </main>
    </div>
  );
}
